before_install: gem install bundler --pre
dist: trusty
language: ruby
services:
  - redis
  - postgres
addons:
  postgresql: "10"
  apt:
    packages:
      - postgresql-10
      - postgresql-client-10
env:
  global:
    - PGPORT=5433
rvm:
  - 2.5.1
script:
  - bundle exec rspec
branches:
  only:
    - master # We want to build PRs, and merges to master
before_script:
  - redis-cli info
  - psql -c 'create database meow_now_test'
  - bundle exec rake db:schema:load
cache:
  bundler: true
install:
  - bundle install
notifications:
  email:
    on_success: never
